# Generated by Django 5.0.6 on 2024-06-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Приём', 'verbose_name_plural': 'Приёмы'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Диагноз', 'verbose_name_plural': 'Диагнозы'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Заболевание', 'verbose_name_plural': 'Заболевания'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Рекомендация', 'verbose_name_plural': 'Рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name': 'Симптом', 'verbose_name_plural': 'Симптомы'},
        ),
    ]
