# Generated by Django 5.0.6 on 2024-06-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0002_alter_appointment_options_alter_diagnosis_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_card.diagnosis', verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_card.document', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_card.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='symptoms',
            field=models.ManyToManyField(to='medical_card.symptom', verbose_name='Симптомы, озвученные на осмотре'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_card.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_card.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(to='medical_card.symptom', verbose_name='Симптомы, соответствующие заболеванию'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_card.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя Фамилия'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='content',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_card.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
    ]
