# Generated by Django 5.0.6 on 2024-06-14 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0003_alter_appointment_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата осмотра'),
        ),
    ]
