# Generated by Django 5.0.6 on 2024-06-14 13:27

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0004_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='author',
            field=models.CharField(max_length=200, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 13, 27, 14, 572170, tzinfo=datetime.timezone.utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата осмотра'),
        ),
    ]
