# Generated by Django 5.0.6 on 2024-06-14 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0005_recommendation_author_recommendation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
