# Generated by Django 5.0.6 on 2024-06-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0006_alter_recommendation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Автор'),
        ),
    ]
