# Generated by Django 5.0.6 on 2024-06-14 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0007_alter_recommendation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата постановки диагноза'),
        ),
    ]
