# Generated by Django 5.0.6 on 2024-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0008_diagnosis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
    ]
