# Generated by Django 5.0.6 on 2024-06-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0009_patient_first_name_patient_second_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
