# Generated by Django 5.0.6 on 2024-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0010_rename_second_name_patient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.FileField(upload_to='images/'),
        ),
    ]
