# Generated by Django 5.0.6 on 2024-06-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_card', '0011_alter_document_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
    ]
